### PR TITLE
Updates Sign In And Sign Up Pages

### PR DESCRIPTION
**Pull request by TheSentry1**
## Describe your changes

Updates the sing in/up pages to the non-prototype versions.
## Checklist before submitting as a pull request
- [X] I have submitted this code through a merge request from a separate branch
- [X] I have performed a self-review of my code
- [X] Will this be part of a product update? If yes, please write one phrase about this update.
The new version is better and works properly.

<details>
<summary>Screenshots&Videos</summary>
Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

### CODE REVIEW

**Review by Jakub-Jedruszczak — COMMENTED** [review]
Good change, it works now. All we need is the backend.

**Review by Jakub-Jedruszczak — APPROVED** [review]
Approved.

**Comment by TheSentry1** [comment]
nice have we decided who is doing backend ? and what we need for the
backend

**Comment by Jakub-Jedruszczak** [comment]
No, we have not decided that yet. Would you be willing to, given you wrote the signup page's code?

**Comment by TheSentry1** [comment]
i have no idea what pragging languages are needed for backend but if can
tell me what research i need to do e.g. what programming languages i will
need to learn and what the final outcome will be for example what should
the backend coding should do then yea i can give it a go

**Comment by Jakub-Jedruszczak** [comment]
Hosting a webserver using JavaScript should be fairly trivial, with the database itself being an implementation/ framework of SQL, as you have learned about it in the first year of your degree. There are many SQL frameworks exist, such as PostgreSQL, CockroachDB, MSSQL, MySQL, or MariaDB; Knex.js (https://knexjs.org/guide/) is a SQL query builder for Node JS, meaning that it is compatible with our website's frontend. 
I hope that helps.

**Comment by TheSentry1** [comment]
Hosting a web server is not what i am worried about i already have a good
idea on how to host a website i will use node js and postgreSQL as i have
experience on those 2 the most - we need to wait for Katie if it is a good
idea to do a login page or not

**Pull request merged**
